name: Imervue Stable Python3.12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build Imervue
      run: pyinstaller --noconfirm --onedir --windowed --icon "Imervue.ico" --name "Imervue" --add-data "Imervue.ico;." --paths ".venv" --hidden-import "imageio" --copy-metadata "imageio" --distpath output "Imervue/__main__.py"
    - name: Debug run Imervue
      run: xvfb-run -s "-screen 0 1280x1024x24" output/Imervue/Imervue.exe --debug --software_opengl